export const Items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "50 جنية",
    category: "فطار",
    imgUrl: "m1.png",
  },
  {
    id: Math.random(),
    title: "وجبة غدا",
    description: "وصف الفطار",
    price: "30 جنية",
    category: "غدا",
    imgUrl: "m2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف الفطار",
    price: "40 جنية",
    category: "عشاء",
    imgUrl: "m3.png",
  },
  {
    id: Math.random(),
    title: "وجبة غدا ممتاز",
    description: "وصف الفطار",
    price: "100 جنية",
    category: "غدا",
    imgUrl: "m1.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء درجة أولى",
    description: "وصف الفطار",
    price: "150 جنية",
    category: "عشاء",
    imgUrl: "m2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "50 جنية",
    category: "فطار",
    imgUrl: "m3.png",
  },
];
